# Generated by Django 4.1.3 on 2022-11-22 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('a', models.IntegerField(verbose_name='A')),
                ('b', models.IntegerField(verbose_name='B')),
                ('c', models.IntegerField(verbose_name='C')),
            ],
        ),
    ]
